### ISSUE TITLE
Environment for Mac M2

### ISSUE THREAD

**Issue by hnguyentt** [chevrettelab/gator-gc#2]
Dear team,

Thanks for your nice package! I'm using Mac M2 and when I use `conda env create -f gator-gc_env.yml` as your instruction I found this error:

```bash
Channels:
 - conda-forge
 - defaults
 - bioconda
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - hmmer=3.3.2*
  - diamond=2.1.6*

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://conda.anaconda.org/bioconda/osx-arm64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

When I changed the environment file like this, the package worked on my Mac M2:
```yml
name: gator-gc
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9.16
  - pandas=1.5.0
  - numpy=1.24.2
  - seaborn=0.12.2
  - matplotlib=3.8.0
  - scipy=1.10.1
  - pygenomeviz=0.4.4
  - biopython=1.81
  - pip=23.0
  - HMMER
```

Hope that you can update environment file for Mac users.

Best,
Hoa
